- name: Installing NGINX
  apt:
    pkg: nginx
    state: latest
  notify: Start Nginx

- name: Creating project folder
  file: path=/var/www/mysite state=directory mode=0755

- name: Copying file index.html
  copy: src=roles/nginx/files/index.html dest=/var/www/mysite/index.html mode=0644

- name: Copying configuration template
  template:
    src: roles/nginx/templates/nginx.conf.j2
    dest: /etc/nginx/sites-available/mysite
  with_items:
    - nginx_port
    - nginx_root_path
  notify: restart nginx

- name: Creating symbolic link
  file: src=/etc/nginx/sites-available/mysite dest=/etc/nginx/sites-enabled/mysite state=link
